#!/bin/bash

# Extension Perl: prerequisites
sudo apt install -y build-essential libanyevent-perl libclass-refresh-perl libcompiler-lexer-perl \
libdata-dump-perl libio-aio-perl libjson-perl libmoose-perl libpadwalker-perl \
libscalar-list-utils-perl libcoro-perl

echo "yes" | sudo cpan Perl::LanguageServer

# # Julia package (most important is Revise.jl, which is needed for the Julia LSP to work)
#     julia -e 'using Pkg; Pkg.add(["Revise", "Pluto"]);'

# # Sage
#     apt-get -y update && apt-get -y upgrade
#     apt install wget
#     # Install Miniforge
#         # Source: https://github.com/conda-forge/miniforge
#         wget -O Miniforge3.sh "https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-$(uname)-$(uname -m).sh"
#         bash Miniforge3.sh -b -p "${HOME}/conda"
#         source "${HOME}/conda/etc/profile.d/conda.sh"
#         # For mamba support also run the following command
#         source "${HOME}/conda/etc/profile.d/mamba.sh"
#         conda activate
#     # Install Sage
#         mamba -y create -n sage sage
#         conda activate sage
#     # Post-install setup
#         # Install pyflakes for automatic syntax checking
#             sage -pip install pyflakes

# # After creating the GitHub Codespace, run the following commands to make Sage available:
# # source "${HOME}/conda/etc/profile.d/conda.sh"; conda activate sage; sage -n --allow-root jupyter